name: risk_tolerance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy  
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - jupyterlab
  - statsmodels
  - pip
  - pip:
      - pandas_datareader
      - plotly
      - xgboost
      - catboost  
      - lightgbm
      - yfinance


      